<?php 
/**
 * 
 */
namespace App\Helpers;
use Auth;
use App\Models\Company;

class SendSMS
{
	static $api_key;
    static $company;

	public function __construct()
    {
        self::$company = Company::find(Auth::user()->company_id);

        self::$api_key = self::$company->api_key;
    }
    static function getBalance()
    {
        $url = "http://api.v2.masgsm.com.tr/v2/get/balance";
        $response = self::MASGSM($url);
        $result = json_decode($response);
        return $result;
    }

    public function getTitle()
    {
        $url = "http://api.v2.masgsm.com.tr/v2/get/originators";
        $response = self::MASGSM($url);
        $result = json_decode($response);
        return $result;
    }

    public function sendSms($sms,$tel)
    {
      
        $url = "http://api.v2.masgsm.com.tr/v2/sms/basic";
        $body = 
            [
                "originator"=>self::$company->sms_title,
                "message"=>$sms,
                "to"=>[$tel],
                "encoding"=>"default"
            ];
        
        $response = self::MASGSM($url,$body);
        $result = json_decode($response);
        return $result;
    }

    static function test($Url, $body = null)
    {
        $API_KEY = self::$api_key;

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'notify.eskiz.uz/api/auth/login');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        $post = array(
            'email' => 'test@eskiz.uz',
            'password' => 'j6DWtQjjpLDNjWEk74Sx'
        );
        curl_setopt($ch, CURLOPT_POSTFIELDS, $post);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        dd($result);
    }

}